/**
 * create the prefix comment of the generated file
 *
 * @param disabledFormat whether disabled format
 */
export function createPrefixCommentOfGenFile(disabledFormat = true) {
  const prefix = `/* eslint-disable */
/* prettier-ignore */
`;
  let comment = `// Generated by @xpress-core/file-router
// Read more: https://github.com/Rascal-coder/Xpress/packages/@core/file-router
`;

  if (disabledFormat) {
    comment = prefix + comment;
  }

  return comment;
}
