packages:
  - internal/*
  - internal/lint-configs/*
  - packages/*
  - apps/*
  - scripts/*
  - docs
  - playground
catalog:
  "@changesets/git": ^3.0.1
  "@clack/prompts": ^0.8.1
  "@commitlint/cli": ^19.5.0
  "@commitlint/config-conventional": ^19.5.0
  "@eslint/js": ^9.15.0
  "@faker-js/faker": ^9.2.0
  "@iconify/json": ^2.2.273
  "@iconify/tailwind": ^1.1.3
  "@jspm/generator": ^2.4.1
  "@manypkg/get-packages": ^2.2.2
  "@pnpm/workspace.read-manifest": ^2.2.1
  "@stylistic/stylelint-plugin": ^3.1.1
  "@tailwindcss/nesting": 0.0.0-insiders.565cd3e
  "@tailwindcss/typography": ^0.5.15
  "@types/archiver": ^6.0.3
  "@types/eslint": ^9.6.1
  "@types/html-minifier-terser": ^7.0.2
  "@types/jsonwebtoken": ^9.0.7
  "@types/node": ^22.9.0
  "@types/postcss-import": ^14.0.3
  "@types/react": ^18.3.12
  "@types/react-dom": ^18.3.1
  "@typescript-eslint/eslint-plugin": ^8.14.0
  "@typescript-eslint/parser": ^8.14.0
  "@vitejs/plugin-react": ^4.3.3
  archiver: ^7.0.1
  autoprefixer: ^10.4.20
  cac: ^6.7.14
  chalk: ^5.3.0
  cheerio: ^1.0.0
  circular-dependency-scanner: ^2.3.0
  commitlint-plugin-function-rules: ^4.0.1
  consola: ^3.2.3
  cssnano: ^7.0.6
  cz-git: ^1.11.0
  czg: ^1.11.0
  dayjs: ^1.11.13
  depcheck: ^1.4.7
  dotenv: ^16.4.5
  eslint: ^9.15.0
  eslint-config-turbo: ^2.3.0
  eslint-plugin-command: ^0.2.6
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-plugin-import-x: ^4.4.2
  eslint-plugin-jsdoc: ^50.5.0
  eslint-plugin-jsonc: ^2.18.2
  eslint-plugin-n: ^17.13.2
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-perfectionist: ^3.9.1
  eslint-plugin-prettier: ^5.2.1
  eslint-plugin-react: ^7.37.2
  eslint-plugin-react-hooks: ^5.0.0
  eslint-plugin-react-refresh: ^0.4.14
  eslint-plugin-regexp: ^2.7.0
  eslint-plugin-unicorn: ^56.0.0
  eslint-plugin-unused-imports: ^4.1.4
  eslint-plugin-vitest: ^0.5.4
  execa: ^9.5.1
  find-up: ^7.0.0
  get-port: ^7.1.0
  globals: ^15.12.0
  h3: ^1.13.0
  html-minifier-terser: ^7.2.0
  jsonc-eslint-parser: ^2.4.0
  jsonwebtoken: ^9.0.2
  nitropack: ^2.10.4
  ora: ^8.1.1
  pkg-types: ^1.2.1
  postcss: ^8.4.49
  postcss-import: ^16.1.0
  postcss-preset-env: ^10.1.1
  postcss-scss: ^4.0.9
  postcss-styled-syntax: ^0.7.0
  prettier: ^3.3.3
  prettier-plugin-tailwindcss: ^0.6.8
  publint: ^0.2.12
  react: ^18.3.1
  react-dom: ^18.3.1
  rimraf: ^6.0.1
  rollup-plugin-visualizer: ^5.12.0
  stylelint: ^16.10.0
  stylelint-config-css-modules: ^4.4.0
  stylelint-config-recess-order: ^5.1.1
  stylelint-config-recommended: ^14.0.1
  stylelint-config-recommended-scss: ^14.1.0
  stylelint-config-standard: ^36.0.1
  stylelint-order: ^6.0.4
  stylelint-prettier: ^5.0.2
  stylelint-scss: ^6.9.0
  tailwindcss-animate: ^1.0.7
  turbo: ^2.3.0
  typescript: ^5.6.3
  unbuild: ^2.0.0
  vite: ^5.4.11
  vite-plugin-compression: ^0.5.1
  vite-plugin-dts: ^4.3.0
  vite-plugin-html: ^3.2.2
  vite-plugin-pwa: ^0.21.0
